version: "3"
services:
  postgres:
    image: "postgres:latest" # Use the official postgres image
  redis:
    image: "redis:latest" # Use the official redis image
  server :
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432
      - REDIS_URL=redis://redis:6379