version: "3"
services:
  postgres:
    image: "postgres:latest" # Use the official postgres image
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest" # Use the official redis image
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    depends_on:
      - api
      - client
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  
  api :
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
   