name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install
        working-directory: ./server

      - run: npm test
        working-directory: ./server

      - run: npm install
        working-directory: ./worker

      - run: npm test
        working-directory: ./worker

      - run: npm install
        working-directory: ./client

      - run: npm test
        working-directory: ./client

      - run: npm run build
        working-directory: ./client

      - uses: docker/login-action@v2.1.0
        with:
          username: kimutaieddy
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - run: |
          docker build -t kimutaieddy/server:latest -f ./server/Dockerfile ./server
          docker build -t kimutaieddy/nginx:latest -f ./nginx/Dockerfile ./nginx
          docker build -t kimutaieddy/worker:latest -f ./worker/Dockerfile ./worker
          docker build -t kimutaieddy/client:latest -f ./client/Dockerfile ./client

      - run: |
          docker push kimutaieddy/server:latest
          docker push kimutaieddy/nginx:latest
          docker push kimutaieddy/worker:latest
          docker push kimutaieddy/client:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add steps for any build or pre-deployment tasks here

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: 'multi-docker'
        environment_name: 'MultiDocker-env'
        region: 'us-east-1'
        version_label: 'some-version'
        bucket_name: 'elasticbeanstalk-us-east-1-891376912432'
        bucket_key: 'docker-multi/${{ github.sha }}.zip'
        wait_for_deployment: true