name: CI/CD Pipeline

on:
  push:
    branches:
      - kimutaieddy-patch-1
  pull_request:
    branches:
      - kimutaieddy-patch-1

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies for server
      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      # Run tests for server
      - name: Run server tests
        run: npm test
        working-directory: ./server

      # Install dependencies for worker
      - name: Install worker dependencies
        run: npm install
        working-directory: ./worker

      # Run tests for worker
      - name: Run worker tests
        run: npm test
        working-directory: ./worker

      # Install dependencies for client (React) project
      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      # Run tests for client (React) project
      - name: Run client tests
        run: npm test
        working-directory: ./client

      # Build production version of client (React) project
      - name: Build client project
        run: npm run build
        working-directory: ./client

      # Debugging Step: List directories
      - name: List directory contents
        run: |
          echo "Server directory:"
          ls -l ./server
          echo "Worker directory:"
          ls -l ./worker
          echo "Client directory:"
          ls -l ./client
          echo "Nginx directory:"
          ls -l ./nginx

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kimutaieddy
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and tag Docker images
      - name: Build and tag Docker images
        run: |
          docker build -t kimutaieddy/server:latest -f ./server/Dockerfile ./server
          docker build -t kimutaieddy/nginx:latest -f ./nginx/Dockerfile ./nginx
          docker build -t kimutaieddy/worker:latest -f ./worker/Dockerfile ./worker
          docker build -t kimutaieddy/client:latest -f ./client/Dockerfile ./client

      # Push Docker images to Docker Hub
      - name: Push Docker images
        run: |
          docker push kimutaieddy/server:latest
          docker push kimutaieddy/nginx:latest
          docker push kimutaieddy/worker:latest
          docker push kimutaieddy/client:latest
